"""Add security_policy to mado_sessions

Revision ID: cb3060c69bea
Revises: b2c3d4e5f6a7
Create Date: 2026-06-08 10:34:22.943724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import shogun.db.base

# revision identifiers, used by Alembic.
revision: str = 'cb3060c69bea'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mado_sessions', sa.Column('security_policy', shogun.db.base.JSONType(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mado_sessions', 'security_policy')
    # ### end Alembic commands ###
